project_id = "thrwpxiahqgubjkjnkgt"

[functions.analyze-watch-metadata]
verify_jwt = false

[functions.search-watch-info]
verify_jwt = false

[functions.suggest-watches]
verify_jwt = false

[functions.fetch-watch-price]
verify_jwt = false

[functions.import-spreadsheet-data]
verify_jwt = false

[functions.analyze-sentiment]
verify_jwt = false

[functions.extract-warranty-info]
verify_jwt = false

[functions.identify-watch-from-photo]
verify_jwt = false